spring:
  main:
    web-application-type: none

optimize:
  baseUrl: <optimize-base-url>
  reportId: <report-id>
  client-id: <client_id>
  client-secret: <client_secret>
  token-base-url: https://login.cloud.camunda.io/oauth/token

xes-mapping:
  base-path: <xes-result-filename-or-path>.xml
