spring:
  main:
    web-application-type: none
  banner:
    location: classpath:banner.txt

optimize:
  baseUrl: <optimize-base-url>
  reportId: <report-id>
  client-id: <client_id>
  client-secret: <client_secret>
  token-base-url: https://login.cloud.camunda.io/oauth/token

xes-mapping:
  # Optionally: Specify the base bath for the resulting XML(s).
  base-path:
